# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    tags:
      - "*"
    paths:
      - README.md

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  one:
    runs-on: ubuntu-latest
    outputs:
      v1var: ${{ steps.step1.outputs.v1 }}
      v2var: ${{ steps.step1.outputs.v2 }}
    strategy:
      matrix:
        foo: [v1, v2]
    steps:
      - id: step1
        run: echo "::set-output name=${{ matrix.foo }}::${{ matrix.foo }}"
        env:
          REPOSECRET: ${{ secrets.REPOSECRET }}
  two:
    runs-on: ubuntu-latest
    needs: one
    steps:
      - run: echo '${{ needs.one.outputs.v1var }}'
      - run: echo '${{ needs.one.outputs.v2var }}'
      - run: echo '${{ toJson(needs.one.outputs) }}'
